### ISSUE TITLE
Tool Conflicts with Publish Points, and No Way to Turn It Off

### ISSUE THREAD

**Issue by DavidMerzJr** [marip8/rviz_tool_cursor#16]
This package contains tools that publish poses on a unique topic.  This topic is used in a number of systems I am responsible for maintaining.

As of f81dc0f63038676d18750c9d647b42782362dd84, the rviz_tool_cursor tools **also** publish 'point' messages on the topic created by the 'publish point' tool.  Because they are both rviz plugins / tools, they publish from the same node, making remapping one or the other infeasible.  I am not sure of any way to distinguish between the outputs of these two tools.  This heavily limits the parallel usage of the publish point tool and the tools from this package.

Is there some straightforward way to make it optional whether the tools publish on both topics?  I don't know how to get constructor arguments in, or even where these constructors are 'called'.  Could we have it check a parameter?

I could just fork the repository and never look back, but I don't like creating parallel development streams without good reason.

**Comment by marip8** [comment]
Per our conversation, you can change the topic on which the point and pose messages are published using the Rviz `ToolProperties` panel such that they don't conflict with the other Rviz tools. I believe this change can be saved as a part of the Rviz config file. I would be open to accepting a PR to change the default topic name of the point publisher too
